src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 */
class Property
{

    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(min=5, max=255)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @Assert\Regex("/^[0-9]{5}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="property", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @Assert\All({
     *   @Assert\Image(mimeTypes="image/jpeg")
     * })
     */
    private $pictureFiles;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->updated_at = new \DateTime();
        $this->options = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function getPicture(): ?Picture
    {
        if ($this->pictures->isEmpty()) {
            return null;
        }
        return $this->pictures->first();
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setProperty($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getProperty() === $this) {
                $picture->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * @param mixed $pictureFiles
     * @return Property
     */
    public function setPictureFiles($pictureFiles): self
    {
        foreach($pictureFiles as $pictureFile) {
            $picture = new Picture();
            $picture->setImageFile($pictureFile);
            $this->addPicture($picture);
        }
        $this->pictureFiles = $pictureFiles;
        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class,[
                'required' => true,
                'label' => 'Titre'
            ])
            ->add('description')
            ->add('surface')
            ->add('rooms', IntegerType::class,[
                'required' => true,
                'label' => 'Nombre de pièces'
            ])
            ->add('bedrooms', IntegerType::class,[
                'required' => true,
                'label' => 'Nombre de chambres'
            ])
            ->add('floor', IntegerType::class,[
                'required' => true,
                'label' => 'Nombre d\'étages'
            ])
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices(),
                'label' => 'Chauffage'
            ])
            ->add('pictureFiles', FileType::class, [
                'required' => false,
                'multiple' => true, 
                'label' => 'Chargement d\'images (jpeg uniquement)'
            ])
            ->add('city', TextType::class,[
                'required' => true,
                'label' => 'Ville'])
            ->add('address', TextType::class,[
                'required' => true,
                'label' => 'Adresse'])
            ->add('postal_code', IntegerType::class,[
                'required' => true,
                'label' => 'Code postal'
            ])
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach($choices as $k => $v) {
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Data\PropertyData;
use App\Entity\Property;
use App\Entity\Contact;
use App\Form\ContactType;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;


class PropertyController extends AbstractController
{
   
    /**
     * @var PropertyRepository
     */
    private $repository;
    /**
     * @var EntityManagerInterface 
     */
    private $em;

   public function __construct(PropertyRepository $repository, EntityManagerInterface $em)
   {
       $this->repository = $repository;
      $this->em = $em;
   }
    /**
     * @Route("/biens", name="property.index")
     * @return Response
     */
    public function index(Request $request, PaginatorInterface $paginator): Response
    {  
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);
        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1),
            6
        );
        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'form'         => $form->createView(),
            'properties' => $properties
        ]);
    }
    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     * @return Response
     */
    public function show(Property $property, string $slug, Request $request, ContactNotification $notification): Response
    {
        if ($property->getSlug() !== $slug) {
            return $this->redirectToRoute('property.show', [
                'id'   => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }

        $contact = new Contact();
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $notification->notify($contact);
            $this->addFlash('success', 'Votre email a bien été envoyé');
            return $this->redirectToRoute('property.show', [
                'id'   => $property->getId(),
                'slug' => $property->getSlug()
            ]);
        }

        return $this->render('property/show.html.twig', [
            'property'     => $property,
            'current_menu' => 'properties',
            'form'         => $form->createView()
        ]);
    }

}

templates/property/_filter.html.twig
{{ form_start(form) }}
    {{ form_row(form.job) }}
    {{ form_row(form.city) }}

    <h4>Prix</h4>
        <div class="row">
            <div class="col-md-6">
                {{ form_row(form.min) }}
            </div>
            <div class="col-md-6">
                {{ form_row(form.max) }}
            </div>
        </div>
        <div id="salary-slider" data-min="{{ min }}" data-max="{{ max }}" style="margin-bottom: 3rem;"></div>
        <p>
 
        <button type="submit" class="btn btn-primary w-100">Filtrer</button>
        
{{ form_end(form) }}

templates/property/_property.html.twig
<div class="card mb-4">
  {% if property.picture %}
    <img src="{{ vich_uploader_asset(property.picture, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height:auto;">
    {% else %}
      <img src="{{ '/images/properties/empty.jpg' | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height:auto;">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">
      <a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">
        {{ property.title }}
      </a>
    </h5>
    <p class="card-text">{{ property.surface }} m² - {{ property.city }} ({{ property.postalCode }})</p>
    <div class="text-primary" style="font-size:2rem; font-weight: bold;">
      {{ property.formattedPrice }} €
    </div>
  </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tous nos bien' %}

{% block body %}
	<div class="jumbotron">
		<div class="container">
			{{ form_start(form) }}
			<div class="form-row align-items-end">
				<div class="col">
					{{ form_row(form.minSurface) }}
				</div>
				<div class="col">
					{{ form_row(form.maxSurface) }}
				</div>
				<div class="col">
					{{ form_row(form.minPrice) }}
				</div>
								<div class="col">
					{{ form_row(form.maxPrice) }}
				</div>
				<div class="col">
					<div class="form-group">
						<button class="btn btn-primary">Rechercher</button>
					</div>
				</div>
			</div>
			{{ form_end(form) }}
		</div>
	</div>
	<div class="container mt-4">
		<h1>Voir tous nos biens</h1>

		<div class="row">
			{% for property in properties %}
				<div class="col-md-4">
					{% include 'property/_property.html.twig' %}
				</div>
			{% endfor %}
		</div>

		<div class="pagination mb-5">
			{{ knp_pagination_render(properties) }}
		</div>
	</div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}

{% block body %}
	<div class="jumbotron">
		<div class="container">

			{% for message in app.flashes('success') %}
				<div class="alert alert-success">
					{{ message }}
				</div>
			{% endfor %}

			<div class="row">
				<div class="col-md-8">
					<div data-slider>
						{% if property.pictures is empty %}
							<img src="{{ '/images/properties/empty.jpg'}}" alt="card-img-top" style="width: 100%; height:auto;">
						{% else %}
							{% if property.pictures|length > 1 %}
								<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
									<div class="carousel-indicators">
										{% for picture in property.pictures %}
											<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ loop.index0 }}" {% if loop.index0 == 0 %} class="active" {% endif %} aria-current="true" aria-label="Slide 1"></button>
										{% endfor %}
									</div>
									<div class="carousel-inner">
										{% for picture in property.pictures %}
											<div {% if loop.index0 == 0 %} class="carousel-item active" {% else %} class="carousel-item" {% endif %}>
												<img src="{{ vich_uploader_asset(picture, 'imageFile')}}" alt="card-img-top" style="width: 100%; height:auto;">
											</div>
										{% endfor %}
									</div>
									<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
										<span class="carousel-control-prev-icon" aria-hidden="true"></span>
										<span class="visually-hidden">Previous</span>
									</button>
									<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
										<span class="carousel-control-next-icon" aria-hidden="true"></span>
										<span class="visually-hidden">Next</span>
									</button>
								</div>
							{% else %}
								{% for picture in property.pictures %}
									<img src="{{ vich_uploader_asset(picture, 'imageFile')}}" alt="card-img-top" style="width: 100%; height:auto;">
								{% endfor %}
							{% endif %}


						{% endif %}
					</div>
				</div>
				<div class="col-md-4">
					<h1>{{ property.title }}</h1>
					<h2>{{ property.rooms }}
						pièces -
						{{ property.surface }}
						m²</h2>
					<div class="text-primary" style="font-size: 4rem;font-weight: bold;">{{ property.formattedPrice }}
						€</div>
					<a href="#" class="btn btn-primary" id="contactButton" {% if form.vars.submitted %} style="display: none;" {% endif %}>Numéro de téléphone de l'agence : 01 44 79 00 29</a>
					<div id="contactForm" class="mt-4" {% if not form.vars.submitted %} style="display: none;" {% endif %}>
						{{ form_start(form) }}
						<div class="row">
							<div class="col">{{ form_row(form.firstname) }}</div>
							<div class="col">{{ form_row(form.lastname) }}</div>
						</div>
						<div class="row">
							<div class="col">{{ form_row(form.phone) }}</div>
							<div class="col">{{ form_row(form.email) }}</div>
						</div>
						{{ form_rest(form) }}
						<div class="form-group">
							<button class="btn btn-primary">Envoyer</button>
						</div>
						{{ form_end(form) }}
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container mt-4">
		<p>
			{{ property.description | nl2br }}
		</p>

		<div class="row">
			<div class="col-md-8 mb-5">
				<h2>Caractéristiques</h2>
				<table class="table table-striped">
					<tr>
						<td>Surface habitable</td>
						<td>{{ property.surface }}
							m²</td>
					</tr>
					<tr>
						<td>Pièces</td>
						<td>{{ property.rooms }}</td>
					</tr>
					<tr>
						<td>Chambres</td>
						<td>{{ property.bedrooms }}</td>
					</tr>
					<tr>
						<td>Etage</td>
						<td>{{ property.floor }}</td>
					</tr>
					<tr>
						<td>Chauffage</td>
						<td>{{ property.heatType }}</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
{% endblock %}